<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="16" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="74629" started-at="2021-07-09T11:36:05Z" finished-at="2021-07-09T11:37:19Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="74629" started-at="2021-07-09T11:36:05Z" finished-at="2021-07-09T11:37:19Z">
      <class name="railway.account.ChangePasswordTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:railway.account.ChangePasswordTest@3c09711b]" name="beforeClass" is-config="true" duration-ms="1130" started-at="2021-07-09T11:36:25Z" finished-at="2021-07-09T11:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC09()[pri:0, instance:railway.account.ChangePasswordTest@3c09711b]" name="TC09" duration-ms="7337" started-at="2021-07-09T11:36:26Z" description="User can change password" finished-at="2021-07-09T11:36:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC09 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:railway.account.ChangePasswordTest@3c09711b]" name="afterClass" is-config="true" duration-ms="657" started-at="2021-07-09T11:36:34Z" finished-at="2021-07-09T11:36:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- railway.account.ChangePasswordTest -->
      <class name="railway.InterfaceTest.DisplayTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:railway.InterfaceTest.DisplayTest@4590c9c3]" name="beforeClass" is-config="true" duration-ms="1139" started-at="2021-07-09T11:36:53Z" finished-at="2021-07-09T11:36:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC06()[pri:0, instance:railway.InterfaceTest.DisplayTest@4590c9c3]" name="TC06" duration-ms="6319" started-at="2021-07-09T11:36:54Z" description="Additional pages display once user logged in" finished-at="2021-07-09T11:37:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:railway.InterfaceTest.DisplayTest@4590c9c3]" name="afterClass" is-config="true" duration-ms="603" started-at="2021-07-09T11:37:00Z" finished-at="2021-07-09T11:37:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- railway.InterfaceTest.DisplayTest -->
      <class name="railway.login.LoginTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeClass" is-config="true" duration-ms="1106" started-at="2021-07-09T11:37:01Z" finished-at="2021-07-09T11:37:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeMethod" is-config="true" duration-ms="1731" started-at="2021-07-09T11:37:02Z" finished-at="2021-07-09T11:37:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC01()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="TC01" duration-ms="1926" started-at="2021-07-09T11:37:04Z" description="TC01 - User Can Login Into Railway with valid username and password" finished-at="2021-07-09T11:37:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome thai00458@gmail.com] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome thai00458@gmail.com] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at railway.login.LoginTest.TC01(LoginTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterMethod" is-config="true" duration-ms="980" started-at="2021-07-09T11:37:06Z" finished-at="2021-07-09T11:37:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeMethod" is-config="true" duration-ms="513" started-at="2021-07-09T11:37:07Z" finished-at="2021-07-09T11:37:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="TC02" duration-ms="1262" started-at="2021-07-09T11:37:07Z" description="TC02 - User Can not Login Into Railway with blank username" finished-at="2021-07-09T11:37:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterMethod" is-config="true" duration-ms="7" started-at="2021-07-09T11:37:08Z" finished-at="2021-07-09T11:37:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeMethod" is-config="true" duration-ms="513" started-at="2021-07-09T11:37:08Z" finished-at="2021-07-09T11:37:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC03()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="TC03" duration-ms="1311" started-at="2021-07-09T11:37:09Z" description="TC03 - User cannot log into Railway with invalid password " finished-at="2021-07-09T11:37:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterMethod" is-config="true" duration-ms="9" started-at="2021-07-09T11:37:10Z" finished-at="2021-07-09T11:37:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeMethod" is-config="true" duration-ms="566" started-at="2021-07-09T11:37:10Z" finished-at="2021-07-09T11:37:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC04()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="TC04" duration-ms="808" started-at="2021-07-09T11:37:11Z" description="TC04 - Login page displays when un-logged User clicks on Book ticket tab" finished-at="2021-07-09T11:37:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterMethod" is-config="true" duration-ms="7" started-at="2021-07-09T11:37:12Z" finished-at="2021-07-09T11:37:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeMethod" is-config="true" duration-ms="531" started-at="2021-07-09T11:37:12Z" finished-at="2021-07-09T11:37:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC05()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="TC05" duration-ms="3271" started-at="2021-07-09T11:37:12Z" description="System shows message when user enters wrong password several times" finished-at="2021-07-09T11:37:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at railway.login.LoginTest.TC05(LoginTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterMethod" is-config="true" duration-ms="7" started-at="2021-07-09T11:37:15Z" finished-at="2021-07-09T11:37:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="beforeMethod" is-config="true" duration-ms="500" started-at="2021-07-09T11:37:15Z" finished-at="2021-07-09T11:37:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC08()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="TC08" duration-ms="1670" started-at="2021-07-09T11:37:16Z" description="User can&#039;t login with an account hasn&#039;t been activated" finished-at="2021-07-09T11:37:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at railway.login.LoginTest.TC08(LoginTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC08 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterMethod" is-config="true" duration-ms="968" started-at="2021-07-09T11:37:18Z" finished-at="2021-07-09T11:37:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:railway.login.LoginTest@32e6e9c3]" name="afterClass" is-config="true" duration-ms="624" started-at="2021-07-09T11:37:19Z" finished-at="2021-07-09T11:37:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- railway.login.LoginTest -->
      <class name="railway.account.BookTicketTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="beforeClass" is-config="true" duration-ms="1896" started-at="2021-07-09T11:36:05Z" finished-at="2021-07-09T11:36:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="beforeMethod" is-config="true" duration-ms="2638" started-at="2021-07-09T11:36:06Z" finished-at="2021-07-09T11:36:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC014()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="TC014" duration-ms="3936" started-at="2021-07-09T11:36:09Z" description="User can book 1 ticket at a time" finished-at="2021-07-09T11:36:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC014 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="afterMethod" is-config="true" duration-ms="1020" started-at="2021-07-09T11:36:13Z" finished-at="2021-07-09T11:36:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="beforeMethod" is-config="true" duration-ms="502" started-at="2021-07-09T11:36:14Z" finished-at="2021-07-09T11:36:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC015()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="TC015" duration-ms="3067" started-at="2021-07-09T11:36:15Z" description="User can open Book ticket page by clicking on Book ticket link in Train timetable page" finished-at="2021-07-09T11:36:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC015 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="afterMethod" is-config="true" duration-ms="991" started-at="2021-07-09T11:36:18Z" finished-at="2021-07-09T11:36:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="beforeMethod" is-config="true" duration-ms="547" started-at="2021-07-09T11:36:19Z" finished-at="2021-07-09T11:36:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC016()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="TC016" duration-ms="4488" started-at="2021-07-09T11:36:19Z" description="User can cancel a ticket" finished-at="2021-07-09T11:36:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC016 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="afterMethod" is-config="true" duration-ms="988" started-at="2021-07-09T11:36:24Z" finished-at="2021-07-09T11:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:railway.account.BookTicketTest@7946e1f4]" name="afterClass" is-config="true" duration-ms="589" started-at="2021-07-09T11:36:25Z" finished-at="2021-07-09T11:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- railway.account.BookTicketTest -->
      <class name="railway.account.ForgotPasswordTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:railway.account.ForgotPasswordTest@5cc7c2a6]" name="beforeClass" is-config="true" duration-ms="1140" started-at="2021-07-09T11:36:34Z" finished-at="2021-07-09T11:36:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TC012()[pri:0, instance:railway.account.ForgotPasswordTest@5cc7c2a6]" name="TC012" duration-ms="4448" started-at="2021-07-09T11:36:36Z" description="Errors display when password reset token is blank" finished-at="2021-07-09T11:36:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Know-Bug] The System doest not send request to email expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Know-Bug] The System doest not send request to email expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at railway.account.ForgotPasswordTest.TC012(ForgotPasswordTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC012 -->
        <test-method status="FAIL" signature="TC013()[pri:0, instance:railway.account.ForgotPasswordTest@5cc7c2a6]" name="TC013" duration-ms="2717" started-at="2021-07-09T11:36:40Z" description="Errors display if password and confirm password don&#039;t match when resetting password" finished-at="2021-07-09T11:36:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Know-Bug] The System doest not send request to email expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Know-Bug] The System doest not send request to email expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at railway.account.ForgotPasswordTest.TC013(ForgotPasswordTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC013 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:railway.account.ForgotPasswordTest@5cc7c2a6]" name="afterClass" is-config="true" duration-ms="613" started-at="2021-07-09T11:36:43Z" finished-at="2021-07-09T11:36:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- railway.account.ForgotPasswordTest -->
      <class name="railway.account.RegisterTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="beforeClass" is-config="true" duration-ms="1122" started-at="2021-07-09T11:36:43Z" finished-at="2021-07-09T11:36:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="beforeMethod" is-config="true" duration-ms="1750" started-at="2021-07-09T11:36:44Z" finished-at="2021-07-09T11:36:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC07()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="TC07" duration-ms="1901" started-at="2021-07-09T11:36:46Z" description="User can create new account" finished-at="2021-07-09T11:36:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thank you for registering your account] but found [You're here]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thank you for registering your account] but found [You're here]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at railway.account.RegisterTest.TC07(RegisterTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC07 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="afterMethod" is-config="true" duration-ms="21" started-at="2021-07-09T11:36:48Z" finished-at="2021-07-09T11:36:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="beforeMethod" is-config="true" duration-ms="520" started-at="2021-07-09T11:36:48Z" finished-at="2021-07-09T11:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC10()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="TC10" duration-ms="1698" started-at="2021-07-09T11:36:49Z" description="User can&#039;t create account with Confirm password is not the same with Password" finished-at="2021-07-09T11:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC10 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="afterMethod" is-config="true" duration-ms="13" started-at="2021-07-09T11:36:50Z" finished-at="2021-07-09T11:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="beforeMethod" is-config="true" duration-ms="519" started-at="2021-07-09T11:36:50Z" finished-at="2021-07-09T11:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC11()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="TC11" duration-ms="1382" started-at="2021-07-09T11:36:51Z" description="User can&#039;t create account while password and PID fields are empty" finished-at="2021-07-09T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC11 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="afterMethod" is-config="true" duration-ms="8" started-at="2021-07-09T11:36:52Z" finished-at="2021-07-09T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:railway.account.RegisterTest@b97c004]" name="afterClass" is-config="true" duration-ms="611" started-at="2021-07-09T11:36:52Z" finished-at="2021-07-09T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- railway.account.RegisterTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
